/* DSblock model generated by Dymola from Modelica model HGV.BaseClasses.Components.Examples.Room
 Dymola Version 2015 FD01 (64-bit), 2014-11-04 translated this at Thu Sep 10 13:03:50 2015

   */

#include <matrixop.h>
static const char* DymArrays0[2]={"water", "air"};
/* Declaration of C-structs */
/* Prototypes for functions used in model */
DYMOLA_STATIC void Modelica_Fluid_Utilities_checkBoundary(const char*  
  mediumName0_0, StringArray   substanceNames0_0, int  singleState0_0, int  
  definex_0p, RealArray   Xx_0boundary, const char*  modelName0_0);
/* Codes used in model */

/* Flattened Modelica model:

function Modelica.Fluid.Utilities.checkBoundary
input String mediumName;
input String substanceNames[:] "Names of substances";
input Boolean singleState;
input Boolean define_p;
discrete input Real X_boundary[:];
input String modelName(start = "??? boundary ???");
protected 
Integer nX(start = size(X_boundary, 1));
String X_str;
public 
algorithm 
assert( not singleState or singleState and define_p, "
Wrong value of parameter define_p (= false) in model \""+modelName+"\":
The selected medium \""+mediumName+"\" has Medium.singleState=true.
Therefore, an boundary density cannot be defined and
define_p = true is required.
");
for i in (1:nX) loop
assert(X_boundary[i] >= 0.0, "
Wrong boundary mass fractions in medium \""+mediumName+"\" in model \""+modelName+"\":
The boundary value X_boundary("+       String(i, true, 0)+") = "+       String(X_boundary[i], true, 0)+"
is negative. It must be positive.
");
end for;
if (nX > 0 and abs(sum(X_boundary)-1.0) > 1E-010) then 
X_str := "";
for i in (1:nX) loop
X_str := X_str+"   X_boundary["+       String(i, true, 0)+"] = "+       String(X_boundary[i], true, 0)+" \""+substanceNames[i]+"\"\n";
end for;
ModelicaError("The boundary mass fractions in medium \""+mediumName+"\" in model \""+modelName+"\"\n"+"do not sum up to 1. Instead, sum(X_boundary) = "+       String(sum(X_boundary), true, 0)+":\n"+X_str);
end if;
end Modelica.Fluid.Utilities.checkBoundary;

  */
DYMOLA_STATIC void Modelica_Fluid_Utilities_checkBoundary(const char*  
  mediumName0_0, StringArray   substanceNames0_0, int  singleState0_0, int  
  definex_0p, RealArray   Xx_0boundary, const char*  modelName0_0) {
  char*retSMark_=GetStringMark();
  PushContext("Modelica.Fluid.Utilities.checkBoundary")
  {
    /* Declare outputs and temporaries */
    int   nX0_0;
    const char*   Xx_0str;
    MarkObject retmark_ = PushMark();
    nX0_0 = RealSize( Xx_0boundary, 1);
    Xx_0str="";
    /* Start of real code */
      AssertModelica( NOT singleState0_0 OR singleState0_0 AND definex_0p,
        " not singleState or singleState and define_p", StringAdd(StringAdd(
        StringAdd(StringAdd("\nWrong value of parameter define_p (= false) in model \"",
        modelName0_0),"\":\nThe selected medium \""),mediumName0_0),
        "\" has Medium.singleState=true.\nTherefore, an boundary density cannot be defined and\ndefine_p = true is required.\n"));
      {
        int end_ = nX0_0;
        int i0_0_0;
        for(i0_0_0 = 1;i0_0_0 <= end_;i0_0_0 += 1) {
          AssertModelica(RealElement( Xx_0boundary, (SizeType)(i0_0_0)) >= 0.0,
            "X_boundary[i] >= 0.0", StringAdd(StringAdd(StringAdd(StringAdd(
            StringAdd(StringAdd(StringAdd(StringAdd("\nWrong boundary mass fractions in medium \"",
            mediumName0_0),"\" in model \""),modelName0_0),"\":\nThe boundary value X_boundary("),
            Integer2String2(i0_0_0, true, 0)),") = "),Real2String2(RealElement( 
            Xx_0boundary, (SizeType)(i0_0_0)), true, 0)),"\nis negative. It must be positive.\n"));
        }
      }
      if (nX0_0 > 0 AND fabs(Realsum( Xx_0boundary)-1.0) > 1E-010) {
        Xx_0str = "";
        Release();
        {
          int end_ = nX0_0;
          int i0_0_0;
          for(i0_0_0 = 1;i0_0_0 <= end_;i0_0_0 += 1) {
            Xx_0str = StringAdd(StringAdd(StringAdd(StringAdd(StringAdd(
              StringAdd(StringAdd(Xx_0str,"   X_boundary["),Integer2String2(
              i0_0_0, true, 0)),"] = "),Real2String2(RealElement( Xx_0boundary, 
              (SizeType)(i0_0_0)), true, 0))," \""),StringElement( 
              substanceNames0_0, (SizeType)(i0_0_0))),"\"\n");
          }
        }
        ModelicaError(StringAdd(StringAdd(StringAdd(StringAdd(StringAdd(
          StringAdd(StringAdd(StringAdd("The boundary mass fractions in medium \"",
          mediumName0_0),"\" in model \""),modelName0_0),"\"\n"),
          "do not sum up to 1. Instead, sum(X_boundary) = "),Real2String2(
          Realsum( Xx_0boundary), true, 0)),":\n"),Xx_0str));
        Release();
      }
    /* Output section */
    PopMark(retmark_);
    SetStringMark(retSMark_);
    PopContext()
    return ;
  }}
/* DSblock C-code: */

#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="HGV.BaseClasses.Components.Examples.Room";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/dhe/appdata/roaming/dynasim/dymola.lic";
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
W_[0] = 2;
W_[4] = 2;
W_[5] = 2;
W_[6] = 2;
W_[7] = 2;
W_[11] = true;
W_[13] = 2;
W_[17] = false;
W_[23] = 0.01;
W_[24] = 0.99;
W_[34] = false;
W_[42] = 1;
W_[48] = false;
W_[52] = 0.01801528;
W_[53] = 0.0289651159;
W_[58] = 3;
W_[61] = 1;
W_[74] = false;
W_[78] = 0.01801528;
W_[79] = 0.0289651159;
W_[87] = 3;
W_[88] = false;
W_[89] = false;
W_[90] = false;
W_[91] = false;
W_[100] = 2;
W_[101] = 2;
W_[102] = 2;
W_[109] = true;
W_[110] = 2;
W_[124] = 0.01801528;
W_[125] = 0.0289651159;
DYNSetAuxString("water", 0);
DYNSetAuxString("air", 1);
W_[1] = 4;
W_[2] = 3;
W_[3] = 2;
W_[10] = 1;
W_[9] = 293.15;
W_[15] = true;
W_[16] = 24.0;
W_[25] = 101325.0;
W_[26] = 293.15;
W_[27] = 0.01;
W_[28] = 0.99;
W_[29] = 1.2;
W_[31] = 293.15;
W_[35] = 0;
W_[49] = true;
W_[59] = true;
W_[60] = true;
W_[75] = true;
W_[92] = 1;
W_[93] = 293.15;
W_[94] = 0.01;
W_[95] = 0.99;
W_[103] = 2;
W_[105] = 293.15;
W_[108] = 1.0;
W_[120] = true;
W_[121] = true;
W_[134] = 24.0;
W_[142] = 101325.0;
W_[146] = 1.2;
W_[144] = 0.01;
W_[139] = 1014.54;
W_[135] = 0.0;
W_[141] = false;
W_[143] = 293.15;
W_[145] = 0.99;
W_[147] = 1;
W_[83] = -1;
W_[82] = 20.0;
W_[81] = 0.99;
W_[85] = 45300.945;
W_[86] = 0.01;
W_[98] = 0.01;
W_[99] = 0.99;
W_[129] = 0.0;
W_[36] = 0;
W_[132] = 0.0;
W_[39] = -1.0;
Aux_[7] = 0.01;
Aux_[6] = 45300.945;
Aux_[2] = 45300.945;
Aux_[3] = 0.01;
W_[67] = 0.99;
W_[68] = -39136.555;
W_[69] = 288.7959459942998;
W_[70] = 0.028790127130676937;
W_[76] = 20.0;
W_[129] = 0.0;
W_[129] = 0.0;
W_[8] = 101325;
W_[97] = 293.15;
W_[96] = 1.0;
W_[65] = 293.15;
W_[66] = 0.01;
W_[80] = 0.01;
W_[62] = 0.01;
W_[63] = 45300.945;
W_[71] = 293.15;
W_[72] = 0.01;
W_[73] = 0.99;
W_[41] = 1.0;
W_[136] = 0.0;
W_[111] = -1.0;
W_[112] = 1.0;
W_[137] = 45300.945;
W_[138] = 0.01;
W_[18] = -1.0;
W_[19] = 1.0;
W_[56] = 1.0;
BoundParameterSection
AssertModelica(DP_[9] >= 0.0,"sin.p >= 0.0", StringAdd(StringAdd(StringAdd(
  StringAdd(StringAdd(StringAdd("Pressure (= ",Real2String2(DP_[9], true, 0)),
  " Pa) of medium \""),"Air"),"\" is negative\n(Temperature = "),Real2String2(
  DP_[11], true, 0))," K)"));
PopAllMarks();
AssertModelica(DP_[11] >= 200.0 AND DP_[11] <= 423.15,"sin.T >= 200.0 and sin.T <= 423.15",
   StringAdd(StringAdd(StringAdd(StringAdd("\nTemperature T is not in the allowed range\n200.0 K <= (T =",
  Real2String2(DP_[11], true, 0))," K) <= 423.15 K\nrequired from medium model \""),
  "Air"),"\"."));
PopAllMarks();
AssertModelica(DP_[9] >= 0.0,"sin.p >= 0.0", StringAdd(StringAdd(StringAdd(
  StringAdd(StringAdd(StringAdd("Pressure (= ",Real2String2(DP_[9], true, 0)),
  " Pa) of medium \""),"Air"),"\" is negative\n(Temperature = "),"293.15")," K)"));
PopAllMarks();
W_[12] = DP_[1];
if (NewParameters) {
helpvar[0] = fabs(W_[12]);
}
W_[14] = 0.0001*helpvar[0];
W_[30] = W_[8];
W_[22] = 1.1843079200592153E-005*W_[30];
W_[32] = DP_[2];
W_[33] = 1-DP_[2];
W_[38] = DP_[0];
W_[104] = W_[8];
W_[106] = DP_[2];
W_[107] = DP_[3];
W_[140] = 1.1843079200592153E-005*W_[104];
W_[148] = 1006.0*(W_[105]-273.15)*(1-W_[106])+(2501014.5+1860*(W_[105]-273.15))*
  W_[106];
W_[113] = DP_[9];
W_[114] = 1.1843079200592153E-005*W_[113];
W_[128] = 24.0*W_[114];
W_[84] = DP_[9];
Aux_[5] = DP_[13];
W_[55] = DP_[11]-273.15;
W_[54] = 1-DP_[13];
W_[57] = W_[55]*1006*W_[54]+(2501014.5+W_[55]*1860)*DP_[13];
Aux_[4] = W_[57];
Aux_[0] = W_[57];
Aux_[1] = DP_[13];
W_[43] = 1.1843079200592153E-005*DP_[9];
W_[44] = 1-DP_[13];
AssertModelica(W_[44] >= -1E-005 AND W_[44] <= 1.00001,"sin.medium.X[2] >= -1E-005 and sin.medium.X[2] <= 1.00001",
   StringAdd(StringAdd(StringAdd(StringAdd(StringAdd(StringAdd("Mass fraction X[2] = ",
  Real2String2(W_[44], true, 0)),"of substance "),"air"),"\nof medium "),"Air"),
  " is not in the range 0..1"));
PopAllMarks();
W_[45] = W_[57]-84437.5;
W_[46] = 287.0512249529787*W_[54]+461.5233290850878*DP_[13];
W_[47] = divmacro(1,"1",55.508435061791985*DP_[13]+34.52428788658843*(1.0-
  DP_[13]),"55.508435061791985*sin.X[1]+34.52428788658843*(1.0-sin.X[1])");
W_[50] = DP_[11]-273.15;
W_[51] = 1E-005*DP_[9];
W_[64] = 1.1843079200592153E-005*DP_[9];
W_[77] = 1E-005*DP_[9];
W_[123] = 1E-005*W_[113];
InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
W_[20] = 288.15;
W_[115] = 293.15;
W_[118] = 1000.0;
#endif
InitialSection
InitialStartSection
InitialStartSection2
W_[40] = W_[148];
W_[116] = W_[107];
X_[0] = W_[106];
X_[1] = 24.0*W_[22]*(20120.0*(1-W_[32])+2538214.5*W_[32]-84437.5);
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
W_[127] = 20.0;
W_[115] = 293.15;
AssertModelica(W_[113] >= 0.0,"simplifiedRoom.rooVol.dynBal.medium.p >= 0.0", 
  StringAdd(StringAdd(StringAdd(StringAdd(StringAdd(StringAdd("Pressure (= ",
  Real2String2(W_[113], true, 0))," Pa) of medium \""),"Air"),"\" is negative\n(Temperature = "),
  Real2String2(W_[115], true, 0))," K)"));
PopAllMarks();
AssertModelica(GreaterEqual(W_[115],"simplifiedRoom.rooVol.dynBal.medium.T", 
  200.0,"200.0", 0) AND LessEqual(W_[115],"simplifiedRoom.rooVol.dynBal.medium.T",
   423.15,"423.15", 1),"simplifiedRoom.rooVol.dynBal.medium.T >= 200.0 and simplifiedRoom.rooVol.dynBal.medium.T <= 423.15",
   StringAdd(StringAdd(StringAdd(StringAdd("\nTemperature T is not in the allowed range\n200.0 K <= (T =",
  Real2String2(W_[115], true, 0))," K) <= 423.15 K\nrequired from medium model \""),
  "Air"),"\"."));
PopAllMarks();
W_[122] = 20.0;
X_[0] = W_[106];
AssertModelica(GreaterEqual(X_[0],"simplifiedRoom.rooVol.dynBal.medium.Xi[1]", 
  -1E-005,"-1E-005", 2) AND LessEqual(X_[0],"simplifiedRoom.rooVol.dynBal.medium.Xi[1]",
   1.00001,"1.00001", 3),"simplifiedRoom.rooVol.dynBal.medium.Xi[1] >= -1E-005 and simplifiedRoom.rooVol.dynBal.medium.Xi[1] <= 1.00001",
   StringAdd(StringAdd(StringAdd(StringAdd(StringAdd(StringAdd("Mass fraction X[1] = ",
  Real2String2(X_[0], true, 0)),"of substance "),"water"),"\nof medium "),"Air"),
  " is not in the range 0..1"));
PopAllMarks();
W_[126] = 1-X_[0];
W_[40] = 20120.0*W_[126]+2538214.5*X_[0];
W_[117] = W_[40]-84437.5;
X_[1] = W_[128]*W_[117];
InitialSection
Init=false;InitializeData(2);Init=true;
InitialSection2
AssertModelica(fabs(Realsum( RealTemporaryDense( &W_[147], 1, 1))-1) < 1E-005,
  "abs(sum(simplifiedRoom.rooVol.dynBal.s)-1) < 1E-005", "If Medium.nXi > 1, then substance 'water' must be present for one component.'Air'.\nCheck medium model.");
PopAllMarks();
AssertModelica(DP_[13] >= -1E-005 AND DP_[13] <= 1.00001,"sin.X[1] >= -1E-005 and sin.X[1] <= 1.00001",
   StringAdd(StringAdd(StringAdd(StringAdd(StringAdd(StringAdd("Mass fraction X[1] = ",
  Real2String2(DP_[13], true, 0)),"of substance "),"water"),"\nof medium "),
  "Air")," is not in the range 0..1"));
PopAllMarks();
EndInitialSection
AssertModelica(W_[113] >= 0.0,"simplifiedRoom.rooVol.dynBal.medium.p >= 0.0", 
  StringAdd(StringAdd(StringAdd(StringAdd(StringAdd(StringAdd("Pressure (= ",
  Real2String2(W_[113], true, 0))," Pa) of medium \""),"Air"),"\" is negative\n(Temperature = "),
  Real2String2(W_[115], true, 0))," K)"));
PopAllMarks();

OutputSection
AssertModelica(GreaterEqual(X_[0],"simplifiedRoom.rooVol.dynBal.medium.Xi[1]", 
  -1E-005,"-1E-005", 2) AND LessEqual(X_[0],"simplifiedRoom.rooVol.dynBal.medium.Xi[1]",
   1.00001,"1.00001", 3),"simplifiedRoom.rooVol.dynBal.medium.Xi[1] >= -1E-005 and simplifiedRoom.rooVol.dynBal.medium.Xi[1] <= 1.00001",
   StringAdd(StringAdd(StringAdd(StringAdd(StringAdd(StringAdd("Mass fraction X[1] = ",
  Real2String2(X_[0], true, 0)),"of substance "),"water"),"\nof medium "),"Air"),
  " is not in the range 0..1"));
PopAllMarks();
(PushModelContext(1,"Modelica.Fluid.Utilities.checkBoundary(\"Air\", {\"water\", \"air\"}, false, sin.use_p, sin.X, \"FixedBoundary\")")
  Modelica_Fluid_Utilities_checkBoundary("Air", StringTemporaryDense( DymArrays0,
   1, 2), false, W_[59], RealTemporaryDense( &DP_[13], 1, 2), "FixedBoundary"));
PopAllMarks();
(PushModelContext(1,"Modelica.Fluid.Utilities.checkBoundary(\"Air\", {\"water\", \"air\"}, false, true, boundary.X_in_internal, \"MassFlowSource_T\")")
  Modelica_Fluid_Utilities_checkBoundary("Air", StringTemporaryDense( DymArrays0,
   1, 2), false, true, RealTemporaryDense( &W_[98], 1, 2), "MassFlowSource_T"));
PopAllMarks();

DynamicsSection
W_[131] = 0.01-X_[0];
 /* Linear system of equations to solve. */
F_[0] = RememberSimple_(F_[0], 0);
SolveScalarLinearParametric( -W_[128]," -simplifiedRoom.rooVol.dynBal.m",  -
  W_[131]," -der(simplifiedRoom.rooVol.dynBal.mXi[1])", F_[0],"der(simplifiedRoom.rooVol.dynBal.medium.Xi[1])");
 /* End of Equation Block */ 

 /* Linear system of equations to solve. */
W_[117] = RememberSimple_(W_[117], 1);
SolveScalarLinearParametric( -W_[128]," -simplifiedRoom.rooVol.dynBal.m",  -
  X_[1]," -simplifiedRoom.rooVol.dynBal.U", W_[117],"simplifiedRoom.rooVol.dynBal.medium.u");
 /* End of Equation Block */ 

W_[40] = 84437.5+W_[117];
W_[133] = 45300.945-W_[40];
W_[37] = DP_[7]+(IF LessTime(DP_[8], 0) THEN 0 ELSE IF LessTime(DP_[8]+DP_[6], 1)
   THEN divmacro((Time-DP_[8])*W_[38],"(time-simplifiedRoom.ramp.startTime)*simplifiedRoom.ramp.height",
  DP_[6],"simplifiedRoom.ramp.duration") ELSE W_[38]);
W_[20] = 273.15+divmacro(W_[40]-2501014.5*X_[0],"simplifiedRoom.airPorts[1].h_outflow-2501014.5*simplifiedRoom.rooVol.dynBal.medium.Xi[1]",1006
  *(1-X_[0])+1860*X_[0],"1006*(1-simplifiedRoom.rooVol.dynBal.medium.Xi[1])+1860*simplifiedRoom.rooVol.dynBal.medium.Xi[1]");
W_[21] = W_[37]*(1+DP_[5]*(W_[20]-DP_[4]));
F_[1] = W_[133]+W_[21];

AcceptedSection1
W_[116] = 1-X_[0];
AssertModelica(GreaterEqual(W_[116],"simplifiedRoom.rooVol.dynBal.medium.X[2]", 
  -1E-005,"-1E-005", 4) AND LessEqual(W_[116],"simplifiedRoom.rooVol.dynBal.medium.X[2]",
   1.00001,"1.00001", 5),"simplifiedRoom.rooVol.dynBal.medium.X[2] >= -1E-005 and simplifiedRoom.rooVol.dynBal.medium.X[2] <= 1.00001",
   StringAdd(StringAdd(StringAdd(StringAdd(StringAdd(StringAdd("Mass fraction X[2] = ",
  Real2String2(W_[116], true, 0)),"of substance "),"air"),"\nof medium "),"Air"),
  " is not in the range 0..1"));
PopAllMarks();
W_[126] = 1-X_[0];
 /* Linear system of equations to solve. */
W_[127] = RememberSimple_(W_[127], 2);
SolveScalarLinear( -(1006.0*W_[126]+1860.0*X_[0])," -(1006.0*simplifiedRoom.rooVol.dynBal.medium.X_air+1860.0*simplifiedRoom.rooVol.dynBal.medium.Xi[1])",
   2501014.5*X_[0]-W_[40],"2501014.5*simplifiedRoom.rooVol.dynBal.medium.Xi[1]-simplifiedRoom.airPorts[1].h_outflow",
   W_[127],"simplifiedRoom.rooVol.dynBal.medium.dT");
 /* End of Equation Block */ 

W_[115] = 273.15+W_[127];
AssertModelica(GreaterEqual(W_[115],"simplifiedRoom.rooVol.dynBal.medium.T", 
  200.0,"200.0", 0) AND LessEqual(W_[115],"simplifiedRoom.rooVol.dynBal.medium.T",
   423.15,"423.15", 1),"simplifiedRoom.rooVol.dynBal.medium.T >= 200.0 and simplifiedRoom.rooVol.dynBal.medium.T <= 423.15",
   StringAdd(StringAdd(StringAdd(StringAdd("\nTemperature T is not in the allowed range\n200.0 K <= (T =",
  Real2String2(W_[115], true, 0))," K) <= 423.15 K\nrequired from medium model \""),
  "Air"),"\"."));
PopAllMarks();

AcceptedSection2
W_[130] = W_[128]*X_[0];
W_[118] = 287.0512249529787*W_[126]+461.5233290850878*X_[0];
W_[119] = divmacro(1,"1",55.508435061791985*X_[0]+34.52428788658843*(1.0-X_[0]),
  "55.508435061791985*simplifiedRoom.rooVol.dynBal.medium.Xi[1]+34.52428788658843*(1.0-simplifiedRoom.rooVol.dynBal.medium.Xi[1])");
W_[122] = W_[115]-273.15;

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("simplifiedRoom.nPorts", "Number of parts [:#(type=Integer)]", 2,\
 0.0,0.0,0.0,0,517)
DeclareVariable("simplifiedRoom.rooLen", "Length of the room [m]", 4, 0.0,0.0,\
0.0,0,513)
DeclareVariable("simplifiedRoom.rooWid", "Width of the room [m]", 3, 0.0,0.0,0.0,\
0,513)
DeclareVariable("simplifiedRoom.rooHei", "Height of the room [m]", 2, 0.0,1E+100,\
0.0,0,513)
DeclareParameter("simplifiedRoom.QRoo_flow", "Heat generation of the room [W]", 0,\
 1000000, 0.0,0.0,0.0,0,560)
DeclareParameter("simplifiedRoom.m_flow_nominal", "Nominal mass flow rate [kg/s]",\
 1, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("simplifiedRoom.rooVol.energyDynamics", "Formulation of energy balance [:#(type=Modelica.Fluid.Types.Dynamics)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("simplifiedRoom.rooVol.massDynamics", "Formulation of mass balance [:#(type=Modelica.Fluid.Types.Dynamics)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("simplifiedRoom.rooVol.substanceDynamics", "Formulation of substance balance [:#(type=Modelica.Fluid.Types.Dynamics)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("simplifiedRoom.rooVol.traceDynamics", "Formulation of trace substance balance [:#(type=Modelica.Fluid.Types.Dynamics)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("simplifiedRoom.rooVol.p_start", "Start value of pressure [Pa|bar]",\
 101325, 0.0,100000000.0,100000.0,0,513)
DeclareVariable("simplifiedRoom.rooVol.T_start", "Start value of temperature [K|degC]",\
 293.15, 1.0,10000.0,300.0,0,513)
DeclareParameter("simplifiedRoom.rooVol.X_start[1]", "Start value of mass fractions m_i/m [kg/kg]",\
 2, 0.01, 0.0,1.0,0.1,0,560)
DeclareParameter("simplifiedRoom.rooVol.X_start[2]", "Start value of mass fractions m_i/m [kg/kg]",\
 3, 0.99, 0.0,1.0,0.1,0,560)
DeclareVariable("simplifiedRoom.rooVol.mSenFac", "Factor for scaling the sensible thermal mass of the volume [1]",\
 1, 1.0,1E+100,0.0,0,513)
DeclareVariable("simplifiedRoom.rooVol.initialize_p", "= true to set up initial equations for pressure [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,1539)
DeclareVariable("simplifiedRoom.rooVol.m_flow_nominal", "Nominal mass flow rate [kg/s]",\
 0.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("simplifiedRoom.rooVol.nPorts", "Number of ports [:#(type=Integer)]",\
 2, 0.0,0.0,0.0,0,517)
DeclareVariable("simplifiedRoom.rooVol.m_flow_small", "Small mass flow rate for regularization of zero flow [kg/s]",\
 0.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("simplifiedRoom.rooVol.allowFlowReversal", "= true to allow flow reversal in medium, false restricts to design direction (ports[1] -> ports[2]). Used only if model has two ports. [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareVariable("simplifiedRoom.rooVol.V", "Volume [m3]", 24.0, 0.0,0.0,0.0,0,513)
DeclareVariable("simplifiedRoom.rooVol.prescribedHeatFlowRate", "Set to true if the model has a prescribed heat flow at its heatPort [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("simplifiedRoom.rooVol.ports[1].m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 -1.0, -100000.0,100000.0,0.0,0,777)
DeclareAlias2("simplifiedRoom.rooVol.ports[1].p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "sin.p", 1, 7, 9, 4)
DeclareAlias2("simplifiedRoom.rooVol.ports[1].h_outflow", "Specific thermodynamic enthalpy close to the connection point if m_flow < 0 [J/kg]",\
 "simplifiedRoom.airPorts[1].h_outflow", 1, 5, 40, 4)
DeclareAlias2("simplifiedRoom.rooVol.ports[1].Xi_outflow[1]", "Independent mixture mass fractions m_i/m close to the connection point if m_flow < 0 [kg/kg]",\
 "simplifiedRoom.rooVol.dynBal.medium.Xi[1]", 1, 1, 0, 4)
DeclareVariable("simplifiedRoom.rooVol.ports[2].m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 1.0, -100000.0,100000.0,0.0,0,777)
DeclareAlias2("simplifiedRoom.rooVol.ports[2].p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "sin.p", 1, 7, 9, 4)
DeclareAlias2("simplifiedRoom.rooVol.ports[2].h_outflow", "Specific thermodynamic enthalpy close to the connection point if m_flow < 0 [J/kg]",\
 "simplifiedRoom.airPorts[1].h_outflow", 1, 5, 40, 4)
DeclareAlias2("simplifiedRoom.rooVol.ports[2].Xi_outflow[1]", "Independent mixture mass fractions m_i/m close to the connection point if m_flow < 0 [kg/kg]",\
 "simplifiedRoom.rooVol.dynBal.medium.Xi[1]", 1, 1, 0, 4)
DeclareVariable("simplifiedRoom.rooVol.heatPort.T", "Port temperature [K|degC]",\
 288.15, 0.0,1E+100,300.0,0,520)
DeclareVariable("simplifiedRoom.rooVol.heatPort.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("simplifiedRoom.rooVol.T", "Temperature of the fluid [K|degC]", \
"simplifiedRoom.rooVol.heatPort.T", 1, 5, 20, 0)
DeclareAlias2("simplifiedRoom.rooVol.p", "Pressure of the fluid [Pa|bar]", \
"sin.p", 1, 7, 9, 0)
DeclareAlias2("simplifiedRoom.rooVol.Xi[1]", "Species concentration of the fluid [1]",\
 "simplifiedRoom.rooVol.dynBal.medium.Xi[1]", 1, 1, 0, 0)
DeclareVariable("simplifiedRoom.rooVol.rho_start", "Density, used to compute start and guess values [kg/m3|g/cm3]",\
 0.0, 0.0,1E+100,0.0,0,2561)
DeclareVariable("_GlobalScope.Modelica.Media.Interfaces.PartialMixtureMedium.X_default[1]",\
 "Default value for mass fractions of medium (for initialization) [kg/kg]", 0.01,\
 0.0,1.0,0.1,0,2561)
DeclareVariable("_GlobalScope.Modelica.Media.Interfaces.PartialMixtureMedium.X_default[2]",\
 "Default value for mass fractions of medium (for initialization) [kg/kg]", 0.99,\
 0.0,1.0,0.1,0,2561)
DeclareVariable("simplifiedRoom.rooVol.state_default.p", "Absolute pressure of medium [Pa|bar]",\
 101325.0, 0.0,100000000.0,100000.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.state_default.T", "Temperature of medium [K|degC]",\
 293.15, 1.0,10000.0,300.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.state_default.X[1]", "Mass fractions (= (component mass)/total mass  m_i/m) [kg/kg]",\
 0.01, 0.0,1.0,0.1,0,2561)
DeclareVariable("simplifiedRoom.rooVol.state_default.X[2]", "Mass fractions (= (component mass)/total mass  m_i/m) [kg/kg]",\
 0.99, 0.0,1.0,0.1,0,2561)
DeclareVariable("simplifiedRoom.rooVol.rho_default", "Density, used to compute fluid mass [kg/m3|g/cm3]",\
 1.2, 0.0,1E+100,0.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.state_start.p", "Absolute pressure of medium [Pa|bar]",\
 100000.0, 0.0,100000000.0,100000.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.state_start.T", "Temperature of medium [K|degC]",\
 293.15, 1.0,10000.0,300.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.state_start.X[1]", "Mass fractions (= (component mass)/total mass  m_i/m) [kg/kg]",\
 0.0, 0.0,1.0,0.1,0,2561)
DeclareVariable("simplifiedRoom.rooVol.state_start.X[2]", "Mass fractions (= (component mass)/total mass  m_i/m) [kg/kg]",\
 0.0, 0.0,1.0,0.1,0,2561)
DeclareVariable("simplifiedRoom.rooVol.useSteadyStateTwoPort", "Flag, true if the model has two ports only and uses a steady state balance [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,2563)
DeclareAlias2("simplifiedRoom.rooVol.hOut_internal", "Internal connector for leaving temperature of the component [J/kg]",\
 "simplifiedRoom.airPorts[1].h_outflow", 1, 5, 40, 1024)
DeclareAlias2("simplifiedRoom.rooVol.XiOut_internal[1]", "Internal connector for leaving species concentration of the component [1]",\
 "simplifiedRoom.rooVol.dynBal.medium.Xi[1]", 1, 1, 0, 1024)
DeclareAlias2("simplifiedRoom.rooVol.QSen_flow.y", "Value of Real output [W]", \
"simplifiedRoom.rooVol.heatPort.Q_flow", 1, 5, 21, 1024)
DeclareVariable("simplifiedRoom.rooVol.masExc.k", "Constant output value [kg/s]",\
 0, 0.0,0.0,0.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.masExc.y", "Connector of Real output signal [kg/s]",\
 0, 0.0,0.0,0.0,0,2561)
DeclareParameter("simplifiedRoom.QSou.T_ref", "Reference temperature [K|degC]", 4,\
 293.15, 0.0,1E+100,300.0,0,560)
DeclareParameter("simplifiedRoom.QSou.alpha", "Temperature coefficient of heat flow rate [1/K]",\
 5, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("simplifiedRoom.QSou.Q_flow", "[W]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("simplifiedRoom.QSou.port.T", "Port temperature [K|degC]", \
"simplifiedRoom.rooVol.heatPort.T", 1, 5, 20, 4)
DeclareAlias2("simplifiedRoom.QSou.port.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "simplifiedRoom.rooVol.heatPort.Q_flow", -1, 5, 21, 132)
DeclareVariable("simplifiedRoom.ramp.height", "Height of ramps [W]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareParameter("simplifiedRoom.ramp.duration", "Duration of ramp (= 0.0 gives a Step) [s]",\
 6, 36000, 0.0,1E+100,0.0,0,560)
DeclareParameter("simplifiedRoom.ramp.offset", "Offset of output signal [W]", 7,\
 0, 0.0,0.0,0.0,0,560)
DeclareParameter("simplifiedRoom.ramp.startTime", "Output = offset for time < startTime [s]",\
 8, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("simplifiedRoom.ramp.y", "Connector of Real output signal [W]", \
"simplifiedRoom.QSou.Q_flow", 1, 5, 37, 0)
DeclareVariable("simplifiedRoom.airPorts[1].m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 -1.0, -100000.0,100000.0,0.0,0,777)
DeclareAlias2("simplifiedRoom.airPorts[1].p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "sin.p", 1, 7, 9, 4)
DeclareVariable("simplifiedRoom.airPorts[1].h_outflow", "Specific thermodynamic enthalpy close to the connection point if m_flow < 0 [J/kg]",\
 0.0, -100000000.0,100000000.0,1000000.0,0,520)
DeclareAlias2("simplifiedRoom.airPorts[1].Xi_outflow[1]", "Independent mixture mass fractions m_i/m close to the connection point if m_flow < 0 [kg/kg]",\
 "simplifiedRoom.rooVol.dynBal.medium.Xi[1]", 1, 1, 0, 4)
DeclareVariable("simplifiedRoom.airPorts[2].m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 1.0, -100000.0,100000.0,0.0,0,777)
DeclareAlias2("simplifiedRoom.airPorts[2].p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "sin.p", 1, 7, 9, 4)
DeclareAlias2("simplifiedRoom.airPorts[2].h_outflow", "Specific thermodynamic enthalpy close to the connection point if m_flow < 0 [J/kg]",\
 "simplifiedRoom.airPorts[1].h_outflow", 1, 5, 40, 4)
DeclareAlias2("simplifiedRoom.airPorts[2].Xi_outflow[1]", "Independent mixture mass fractions m_i/m close to the connection point if m_flow < 0 [kg/kg]",\
 "simplifiedRoom.rooVol.dynBal.medium.Xi[1]", 1, 1, 0, 4)
DeclareVariable("sin.nPorts", "Number of ports [:#(type=Integer)]", 1, 0.0,0.0,\
0.0,0,517)
DeclareAlias2("sin.medium.p", "Absolute pressure of medium [Pa|bar]", "sin.p", 1,\
 7, 9, 0)
DeclareAlias2("sin.medium.Xi[1]", "Structurally independent mass fractions [1]",\
 "sin.X[1]", 1, 7, 13, 0)
DeclareAlias2("sin.medium.h", "Specific enthalpy of medium [J/kg]", \
"sin.ports[1].h_outflow", 1, 5, 57, 0)
DeclareVariable("sin.medium.d", "Density of medium [kg/m3|g/cm3]", 1, 0.0,\
100000.0,1.0,0,513)
DeclareAlias2("sin.medium.T", "Temperature of medium [K|degC]", "sin.T", 1, 7, 11,\
 0)
DeclareAlias2("sin.medium.X[1]", "Mass fractions (= (component mass)/total mass  m_i/m) [kg/kg]",\
 "sin.X[1]", 1, 7, 13, 0)
DeclareVariable("sin.medium.X[2]", "Mass fractions (= (component mass)/total mass  m_i/m) [kg/kg]",\
 0.99, 0.0,1.0,0.1,0,513)
DeclareVariable("sin.medium.u", "Specific internal energy of medium [J/kg]", 0.0,\
 -100000000.0,100000000.0,1000000.0,0,513)
DeclareVariable("sin.medium.R", "Gas constant (of mixture if applicable) [J/(kg.K)]",\
 1000.0, 0.0,10000000.0,1000.0,0,513)
DeclareVariable("sin.medium.MM", "Molar mass (of mixture or single fluid) [kg/mol]",\
 0.032, 0.001,0.25,0.032,0,513)
DeclareAlias2("sin.medium.state.p", "Absolute pressure of medium [Pa|bar]", \
"sin.p", 1, 7, 9, 0)
DeclareAlias2("sin.medium.state.T", "Temperature of medium [K|degC]", "sin.T", 1,\
 7, 11, 0)
DeclareAlias2("sin.medium.state.X[1]", "Mass fractions (= (component mass)/total mass  m_i/m) [kg/kg]",\
 "sin.X[1]", 1, 7, 13, 0)
DeclareAlias2("sin.medium.state.X[2]", "Mass fractions (= (component mass)/total mass  m_i/m) [kg/kg]",\
 "sin.medium.X[2]", 1, 5, 44, 0)
DeclareVariable("sin.medium.preferredMediumStates", "= true if StateSelect.prefer shall be used for the independent property variables of the medium [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("sin.medium.standardOrderComponents", "If true, and reducedX = true, the last element of X will be computed from the other ones [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareVariable("sin.medium.T_degC", "Temperature of medium in [degC] [degC;]", \
0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sin.medium.p_bar", "Absolute pressure of medium in [bar] [bar]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("sin.medium.MMX[1]", "Molar masses of components [kg/mol]", \
0.01801528, 0.0,1E+100,0.0,0,2561)
DeclareVariable("sin.medium.MMX[2]", "Molar masses of components [kg/mol]", \
0.0289651159, 0.0,1E+100,0.0,0,2561)
DeclareAlias2("sin.medium.X_steam", "Mass fraction of steam water [kg/kg]", \
"sin.X[1]", 1, 7, 13, 1024)
DeclareVariable("sin.medium.X_air", "Mass fraction of air [kg/kg]", 0.0, 0.0,1.0,\
0.1,0,2561)
DeclareVariable("sin.medium.dT", "Temperature difference used to compute enthalpy [K,]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("sin.ports[1].m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 1.0, -1E+060,1E+060,0.0,0,777)
DeclareAlias2("sin.ports[1].p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "sin.p", 1, 7, 9, 4)
DeclareVariable("sin.ports[1].h_outflow", "Specific thermodynamic enthalpy close to the connection point if m_flow < 0 [J/kg]",\
 0.0, -10000000000.0,10000000000.0,1000000.0,0,521)
DeclareAlias2("sin.ports[1].Xi_outflow[1]", "Independent mixture mass fractions m_i/m close to the connection point if m_flow < 0 [kg/kg]",\
 "sin.X[1]", 1, 7, 13, 4)
DeclareVariable("sin.flowDirection", "Allowed flow direction [:#(type=Modelica.Fluid.Types.PortFlowDirection)]",\
 3, 1.0,3.0,0.0,0,2565)
DeclareVariable("sin.use_p", "select p or d [:#(type=Boolean)]", true, 0.0,0.0,\
0.0,0,515)
DeclareParameter("sin.p", "Boundary pressure [Pa|bar]", 9, 101325, 0.0,\
100000000.0,100000.0,0,560)
DeclareParameter("sin.d", "Boundary density [kg/m3|g/cm3]", 10, 1.2, 0.0,\
100000.0,1.0,0,560)
DeclareVariable("sin.use_T", "select T or h [:#(type=Boolean)]", true, 0.0,0.0,\
0.0,0,515)
DeclareParameter("sin.T", "Boundary temperature [K|degC]", 11, 293.15, 1.0,\
10000.0,300.0,0,560)
DeclareParameter("sin.h", "Boundary specific enthalpy [J/kg]", 12, 45300.945, \
-10000000000.0,10000000000.0,1000000.0,0,560)
DeclareParameter("sin.X[1]", "Boundary mass fractions m_i/m [kg/kg]", 13, 0.01, \
0.0,1.0,0.1,0,560)
DeclareParameter("sin.X[2]", "Boundary mass fractions m_i/m [kg/kg]", 14, 0.99, \
0.0,1.0,0.1,0,560)
DeclareVariable("boundary.nPorts", "Number of ports [:#(type=Integer)]", 1, \
0.0,0.0,0.0,0,517)
DeclareAlias2("boundary.medium.p", "Absolute pressure of medium [Pa|bar]", \
"sin.p", 1, 7, 9, 0)
DeclareVariable("boundary.medium.Xi[1]", "Structurally independent mass fractions [1]",\
 0.01, 0.0,1.0,0.0,0,513)
DeclareVariable("boundary.medium.h", "Specific enthalpy of medium [J/kg]", \
45300.945, 0.0,0.0,0.0,0,513)
DeclareVariable("boundary.medium.d", "Density of medium [kg/m3|g/cm3]", 1, 0.0,\
100000.0,1.0,0,513)
DeclareVariable("boundary.medium.T", "Temperature of medium [K|degC]", 293.15, \
1.0,10000.0,300.0,0,513)
DeclareVariable("boundary.medium.X[1]", "Mass fractions (= (component mass)/total mass  m_i/m) [kg/kg]",\
 0.01, 0.0,1.0,0.1,0,513)
DeclareVariable("boundary.medium.X[2]", "Mass fractions (= (component mass)/total mass  m_i/m) [kg/kg]",\
 0.99, 0.0,1.0,0.1,0,513)
DeclareVariable("boundary.medium.u", "Specific internal energy of medium [J/kg]",\
 -39136.555, -100000000.0,100000000.0,1000000.0,0,513)
DeclareVariable("boundary.medium.R", "Gas constant (of mixture if applicable) [J/(kg.K)]",\
 288.7959459942998, 0.0,10000000.0,1000.0,0,513)
DeclareVariable("boundary.medium.MM", "Molar mass (of mixture or single fluid) [kg/mol]",\
 0.028790127130676937, 0.001,0.25,0.032,0,513)
DeclareAlias2("boundary.medium.state.p", "Absolute pressure of medium [Pa|bar]",\
 "sin.p", 1, 7, 9, 0)
DeclareVariable("boundary.medium.state.T", "Temperature of medium [K|degC]", \
293.15, 1.0,10000.0,300.0,0,513)
DeclareVariable("boundary.medium.state.X[1]", "Mass fractions (= (component mass)/total mass  m_i/m) [kg/kg]",\
 0.01, 0.0,1.0,0.1,0,513)
DeclareVariable("boundary.medium.state.X[2]", "Mass fractions (= (component mass)/total mass  m_i/m) [kg/kg]",\
 0.99, 0.0,1.0,0.1,0,513)
DeclareVariable("boundary.medium.preferredMediumStates", "= true if StateSelect.prefer shall be used for the independent property variables of the medium [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareVariable("boundary.medium.standardOrderComponents", "If true, and reducedX = true, the last element of X will be computed from the other ones [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareVariable("boundary.medium.T_degC", "Temperature of medium in [degC] [degC;]",\
 20.0, 0.0,0.0,0.0,0,513)
DeclareVariable("boundary.medium.p_bar", "Absolute pressure of medium in [bar] [bar]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("boundary.medium.MMX[1]", "Molar masses of components [kg/mol]",\
 0.01801528, 0.0,1E+100,0.0,0,2561)
DeclareVariable("boundary.medium.MMX[2]", "Molar masses of components [kg/mol]",\
 0.0289651159, 0.0,1E+100,0.0,0,2561)
DeclareVariable("boundary.medium.X_steam", "Mass fraction of steam water [kg/kg]",\
 0.01, 0.0,1.0,0.1,0,2561)
DeclareVariable("boundary.medium.X_air", "Mass fraction of air [kg/kg]", 0.99, \
0.0,1.0,0.1,0,2561)
DeclareVariable("boundary.medium.dT", "Temperature difference used to compute enthalpy [K,]",\
 20.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("boundary.ports[1].m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 -1, -1E+060,1E+060,0.0,0,777)
DeclareVariable("boundary.ports[1].p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 100000.0, 0.0,100000000.0,100000.0,0,521)
DeclareVariable("boundary.ports[1].h_outflow", "Specific thermodynamic enthalpy close to the connection point if m_flow < 0 [J/kg]",\
 45300.945, -10000000000.0,10000000000.0,1000000.0,0,521)
DeclareVariable("boundary.ports[1].Xi_outflow[1]", "Independent mixture mass fractions m_i/m close to the connection point if m_flow < 0 [kg/kg]",\
 0.01, 0.0,1.0,0.1,0,521)
DeclareVariable("boundary.flowDirection", "Allowed flow direction [:#(type=Modelica.Fluid.Types.PortFlowDirection)]",\
 3, 1.0,3.0,0.0,0,2565)
DeclareVariable("boundary.use_m_flow_in", "Get the mass flow rate from the input connector [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("boundary.use_T_in", "Get the temperature from the input connector [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("boundary.use_X_in", "Get the composition from the input connector [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("boundary.use_C_in", "Get the trace substances from the input connector [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("boundary.m_flow", "Fixed mass flow rate going out of the fluid port [kg/s]",\
 1, -100000.0,100000.0,0.0,0,513)
DeclareVariable("boundary.T", "Fixed value of temperature [K|degC]", 293.15, 1.0,\
10000.0,300.0,0,513)
DeclareVariable("boundary.X[1]", "Fixed value of composition [kg/kg]", 0.01, 0.0,\
1.0,0.1,0,513)
DeclareVariable("boundary.X[2]", "Fixed value of composition [kg/kg]", 0.99, 0.0,\
1.0,0.1,0,513)
DeclareVariable("boundary.m_flow_in_internal", "Needed to connect to conditional connector [kg/s]",\
 1.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("boundary.T_in_internal", "Needed to connect to conditional connector [K]",\
 293.15, 0.0,0.0,0.0,0,2561)
DeclareVariable("boundary.X_in_internal[1]", "Needed to connect to conditional connector [1]",\
 0.01, 0.0,0.0,0.0,0,2561)
DeclareVariable("boundary.X_in_internal[2]", "Needed to connect to conditional connector [1]",\
 0.99, 0.0,0.0,0.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.energyDynamics", "Formulation of energy balance [:#(type=Modelica.Fluid.Types.Dynamics)]",\
 2, 1.0,4.0,0.0,0,2565)
DeclareVariable("simplifiedRoom.rooVol.dynBal.massDynamics", "Formulation of mass balance [:#(type=Modelica.Fluid.Types.Dynamics)]",\
 2, 1.0,4.0,0.0,0,2565)
DeclareVariable("simplifiedRoom.rooVol.dynBal.substanceDynamics", \
"Formulation of substance balance [:#(type=Modelica.Fluid.Types.Dynamics)]", 2, \
1.0,4.0,0.0,0,2565)
DeclareVariable("simplifiedRoom.rooVol.dynBal.traceDynamics", "Formulation of trace substance balance [:#(type=Modelica.Fluid.Types.Dynamics)]",\
 2, 1.0,4.0,0.0,0,2565)
DeclareVariable("simplifiedRoom.rooVol.dynBal.p_start", "Start value of pressure [Pa|bar]",\
 100000.0, 0.0,100000000.0,100000.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.T_start", "Start value of temperature [K|degC]",\
 293.15, 1.0,10000.0,300.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.X_start[1]", "Start value of mass fractions m_i/m [kg/kg]",\
 0.0, 0.0,1.0,0.1,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.X_start[2]", "Start value of mass fractions m_i/m [kg/kg]",\
 0.0, 0.0,1.0,0.1,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.mSenFac", "Factor for scaling the sensible thermal mass of the volume [1]",\
 1.0, 1.0,1E+100,0.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.initialize_p", "= true to set up initial equations for pressure [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,1539)
DeclareVariable("simplifiedRoom.rooVol.dynBal.nPorts", "Number of ports [:#(type=Integer)]",\
 2, 0.0,0.0,0.0,0,2565)
DeclareVariable("simplifiedRoom.rooVol.dynBal.ports[1].m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 -1.0, -100000.0,100000.0,0.0,0,2825)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.ports[1].p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "sin.p", 1, 7, 9, 1028)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.ports[1].h_outflow", \
"Specific thermodynamic enthalpy close to the connection point if m_flow < 0 [J/kg]",\
 "simplifiedRoom.airPorts[1].h_outflow", 1, 5, 40, 1028)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.ports[1].Xi_outflow[1]", \
"Independent mixture mass fractions m_i/m close to the connection point if m_flow < 0 [kg/kg]",\
 "simplifiedRoom.rooVol.dynBal.medium.Xi[1]", 1, 1, 0, 1028)
DeclareVariable("simplifiedRoom.rooVol.dynBal.ports[2].m_flow", "Mass flow rate from the connection point into the component [kg/s]",\
 1.0, -100000.0,100000.0,0.0,0,2825)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.ports[2].p", "Thermodynamic pressure in the connection point [Pa|bar]",\
 "sin.p", 1, 7, 9, 1028)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.ports[2].h_outflow", \
"Specific thermodynamic enthalpy close to the connection point if m_flow < 0 [J/kg]",\
 "simplifiedRoom.airPorts[1].h_outflow", 1, 5, 40, 1028)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.ports[2].Xi_outflow[1]", \
"Independent mixture mass fractions m_i/m close to the connection point if m_flow < 0 [kg/kg]",\
 "simplifiedRoom.rooVol.dynBal.medium.Xi[1]", 1, 1, 0, 1028)
DeclareVariable("simplifiedRoom.rooVol.dynBal.medium.p", "Absolute pressure of medium [Pa|bar]",\
 0.0, 0.0,1E+100,100000.0,0,2561)
DeclareState("simplifiedRoom.rooVol.dynBal.medium.Xi[1]", "Structurally independent mass fractions [1]",\
 0, 0.0, 0.0,1.0,0.1,0,2592)
DeclareDerivative("simplifiedRoom.rooVol.dynBal.medium.der(Xi[1])", \
"der(Structurally independent mass fractions) [s-1]", 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.medium.h", "Specific enthalpy of medium [J/kg]",\
 "simplifiedRoom.airPorts[1].h_outflow", 1, 5, 40, 1024)
DeclareVariable("simplifiedRoom.rooVol.dynBal.medium.d", "Density of medium [kg/m3|g/cm3]",\
 0.0, 0.0,100000.0,1.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.medium.T", "Temperature of medium [K|degC]",\
 293.15, 1.0,10000.0,300.0,0,2560)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.medium.X[1]", "Mass fractions (= (component mass)/total mass  m_i/m) [kg/kg]",\
 "simplifiedRoom.rooVol.dynBal.medium.Xi[1]", 1, 1, 0, 1024)
DeclareVariable("simplifiedRoom.rooVol.dynBal.medium.X[2]", "Mass fractions (= (component mass)/total mass  m_i/m) [kg/kg]",\
 0.0, 0.0,1.0,0.1,0,2560)
DeclareVariable("simplifiedRoom.rooVol.dynBal.medium.u", "Specific internal energy of medium [J/kg]",\
 0.0, -100000000.0,100000000.0,1000000.0,0,2560)
DeclareVariable("simplifiedRoom.rooVol.dynBal.medium.R", "Gas constant (of mixture if applicable) [J/(kg.K)]",\
 1000.0, 0.0,10000000.0,1000.0,0,2560)
DeclareVariable("simplifiedRoom.rooVol.dynBal.medium.MM", "Molar mass (of mixture or single fluid) [kg/mol]",\
 0.032, 0.001,0.25,0.032,0,2560)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.medium.state.p", "Absolute pressure of medium [Pa|bar]",\
 "sin.p", 1, 7, 9, 1024)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.medium.state.T", "Temperature of medium [K|degC]",\
 "simplifiedRoom.rooVol.dynBal.medium.T", 1, 5, 115, 1024)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.medium.state.X[1]", "Mass fractions (= (component mass)/total mass  m_i/m) [kg/kg]",\
 "simplifiedRoom.rooVol.dynBal.medium.Xi[1]", 1, 1, 0, 1024)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.medium.state.X[2]", "Mass fractions (= (component mass)/total mass  m_i/m) [kg/kg]",\
 "simplifiedRoom.rooVol.dynBal.medium.X[2]", 1, 5, 116, 1024)
DeclareVariable("simplifiedRoom.rooVol.dynBal.medium.preferredMediumStates", \
"= true if StateSelect.prefer shall be used for the independent property variables of the medium [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,2563)
DeclareVariable("simplifiedRoom.rooVol.dynBal.medium.standardOrderComponents", \
"If true, and reducedX = true, the last element of X will be computed from the other ones [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,2563)
DeclareVariable("simplifiedRoom.rooVol.dynBal.medium.T_degC", "Temperature of medium in [degC] [degC;]",\
 0.0, 0.0,0.0,0.0,0,2560)
DeclareVariable("simplifiedRoom.rooVol.dynBal.medium.p_bar", "Absolute pressure of medium in [bar] [bar]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.medium.MMX[1]", "Molar masses of components [kg/mol]",\
 0.01801528, 0.0,1E+100,0.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.medium.MMX[2]", "Molar masses of components [kg/mol]",\
 0.0289651159, 0.0,1E+100,0.0,0,2561)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.medium.X_steam", "Mass fraction of steam water [kg/kg]",\
 "simplifiedRoom.rooVol.dynBal.medium.Xi[1]", 1, 1, 0, 1024)
DeclareVariable("simplifiedRoom.rooVol.dynBal.medium.X_air", "Mass fraction of air [kg/kg]",\
 0.0, 0.0,1.0,0.1,0,2560)
DeclareVariable("simplifiedRoom.rooVol.dynBal.medium.dT", "Temperature difference used to compute enthalpy [K,]",\
 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("simplifiedRoom.rooVol.dynBal.U", "Internal energy of fluid [J]", 1,\
 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("simplifiedRoom.rooVol.dynBal.der(U)", "der(Internal energy of fluid) [W]",\
 0.0, 0.0,0.0,0.0,0,2560)
DeclareVariable("simplifiedRoom.rooVol.dynBal.m", "Mass of fluid [kg]", 0.0, 0.0,\
1E+100,0.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.der(m)", "der(Mass of fluid) [kg/s]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.mXi[1]", "Masses of independent components in the fluid [kg]",\
 0.0, 0.0,1E+100,0.0,0,2560)
DeclareVariable("simplifiedRoom.rooVol.dynBal.der(mXi[1])", "der(Masses of independent components in the fluid) [kg/s]",\
 0.0, 0.0,0.0,0.0,0,2560)
DeclareVariable("simplifiedRoom.rooVol.dynBal.mb_flow", "Mass flows across boundaries [kg/s]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.mbXi_flow[1]", "Substance mass flows across boundaries [kg/s]",\
 "simplifiedRoom.rooVol.dynBal.der(mXi[1])", 1, 5, 131, 1024)
DeclareVariable("simplifiedRoom.rooVol.dynBal.Hb_flow", "Enthalpy flow across boundaries or energy source/sink [W]",\
 0.0, 0.0,0.0,0.0,0,2560)
DeclareVariable("simplifiedRoom.rooVol.dynBal.fluidVolume", "Volume [m3]", 24.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.CSen", "Aditional heat capacity for implementing mFactor [J/K]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.Q_flow", "Sensible plus latent heat flow rate transferred into the medium [W]",\
 "simplifiedRoom.rooVol.heatPort.Q_flow", 1, 5, 21, 1024)
DeclareVariable("simplifiedRoom.rooVol.dynBal.mWat_flow", "Moisture mass flow rate added to the medium [kg/s]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.hOut", "Leaving enthalpy of the component [J/kg]",\
 "simplifiedRoom.airPorts[1].h_outflow", 1, 5, 40, 1024)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.XiOut[1]", "Leaving species concentration of the component [1]",\
 "simplifiedRoom.rooVol.dynBal.medium.Xi[1]", 1, 1, 0, 1024)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.ports_H_flow[1]", "[W]", \
"simplifiedRoom.airPorts[1].h_outflow", -1, 5, 40, 1024)
DeclareVariable("simplifiedRoom.rooVol.dynBal.ports_H_flow[2]", "[W]", 45300.945,\
 -100000000.0,100000000.0,1000.0,0,2561)
DeclareAlias2("simplifiedRoom.rooVol.dynBal.ports_mXi_flow[1, 1]", "[kg/s]", \
"simplifiedRoom.rooVol.dynBal.medium.Xi[1]", -1, 1, 0, 1024)
DeclareVariable("simplifiedRoom.rooVol.dynBal.ports_mXi_flow[2, 1]", "[kg/s]", \
0.01, 0.0,0.0,0.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.cp_default", "Heat capacity, to compute additional dry mass [J/(kg.K)]",\
 1014.54, 0.0,0.0,0.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.rho_nominal", "Density, used to compute fluid mass [kg/m3|g/cm3]",\
 0.0, 0.0,1E+100,0.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.computeCSen", "[:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,2563)
DeclareVariable("simplifiedRoom.rooVol.dynBal.state_default.p", "Absolute pressure of medium [Pa|bar]",\
 101325.0, 0.0,100000000.0,100000.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.state_default.T", "Temperature of medium [K|degC]",\
 293.15, 1.0,10000.0,300.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.state_default.X[1]", \
"Mass fractions (= (component mass)/total mass  m_i/m) [kg/kg]", 0.01, 0.0,1.0,\
0.1,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.state_default.X[2]", \
"Mass fractions (= (component mass)/total mass  m_i/m) [kg/kg]", 0.99, 0.0,1.0,\
0.1,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.rho_default", "Density, used to compute fluid mass [kg/m3|g/cm3]",\
 1.2, 0.0,1E+100,0.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.s[1]", "Vector with zero everywhere except where species is [1]",\
 1, 0.0,0.0,0.0,0,2561)
DeclareVariable("simplifiedRoom.rooVol.dynBal.hStart", "Start value for specific enthalpy [J/kg]",\
 0.0, 0.0,0.0,0.0,0,2561)
EndNonAlias(0)
#define NX_    2
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    149
#define NP_    15
#define NPS_   0
#define MAXAuxStr_   2
#define MAXAuxStrLen_   500
#define NHash1_ 1483618632
#define NHash2_ -423538374
#define NHash3_ 0
#define NI_    0
#define NRelF_ 6
#define NRel_  6
#define NTim_  2
#define NSamp_ 0
#define NCons_ 0
#define NA_    53
#define SizePre_ 0
#define SizeEq_ 3
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 8
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 1
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double *time, double X_[], double XD_[], double U_[], 
double DP_[], long IP_[], Dymola_bool LP_[], double F_[], double Y_[], double W_[], double QZ_[], double duser_[], long iuser_[], void*cuser_[]) {
static Real initStore[1];
}
StartDataBlock
StartEqBlock
DoRemember_(F_[0], 0.0, 0);
DoRemember_(W_[127], 0.0, 2);
DoRemember_(W_[117], 0.0, 1);
EndEqBlock
EndDataBlock
